test_average_u_rel (__main__.SpectralMethodTestCase) ... FAIL
test_average_uv_rel (__main__.SpectralMethodTestCase) ... FAIL
test_average_uw_rel (__main__.SpectralMethodTestCase) ... FAIL
test_average_v_rel (__main__.SpectralMethodTestCase) ... ok
test_average_vw_rel (__main__.SpectralMethodTestCase) ... FAIL
test_average_w_rel (__main__.SpectralMethodTestCase) ... ok

======================================================================
FAIL: test_average_u_rel (__main__.SpectralMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/Asus/Documents/циам/uniform_grid_synthetic_turbulance_generator/test.py", line 120, in test_average_u_rel
    self.assertAlmostEqual(0., self.correlations.u_rel, places=3, msg='<u>_rel = %.6f' % self.correlations.u_rel)
AssertionError: 0.0 != 0.0005835924068128053 within 3 places : <u>_rel = 0.000584

======================================================================
FAIL: test_average_uv_rel (__main__.SpectralMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/Asus/Documents/циам/uniform_grid_synthetic_turbulance_generator/test.py", line 130, in test_average_uv_rel
    self.correlations.uv_rel)
AssertionError: 0.0 == -0.0034826461965219296 within 2 places : <uv>_rel = -0.003483

======================================================================
FAIL: test_average_uw_rel (__main__.SpectralMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/Asus/Documents/циам/uniform_grid_synthetic_turbulance_generator/test.py", line 134, in test_average_uw_rel
    self.correlations.uv_rel)
AssertionError: 0.0 == -0.0026263577839881992 within 2 places : <uw>_rel = -0.003483

======================================================================
FAIL: test_average_vw_rel (__main__.SpectralMethodTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/Asus/Documents/циам/uniform_grid_synthetic_turbulance_generator/test.py", line 138, in test_average_vw_rel
    self.correlations.vw_rel)
AssertionError: 0.0 == 0.0017013977967534452 within 2 places : <vw>_rel = 0.001701

----------------------------------------------------------------------
Ran 6 tests in 1639.104s

FAILED (failures=4)
